version: "3"
services:
  app:
    container_name: funBox
    ports:
      - "8081:8080"
    build: .
    restart: unless-stopped
    links:
      - mymongodbfunbox
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mymongodbfunbox:
    container_name: mymongodatabase
    image: mongo
    ports:
      - "27019:27017"
    restart: unless-stopped
    volumes:
      - ../data:/data/db